// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyf6o8n0UfePzVSvyTtyyWEJoDFoKgSv0',
    appId: '1:130658554754:web:16727c3c631a453a76f59b',
    messagingSenderId: '130658554754',
    projectId: 'fitness-e29b5',
    authDomain: 'fitness-e29b5.firebaseapp.com',
    storageBucket: 'fitness-e29b5.appspot.com',
    measurementId: 'G-L2WPTNM0F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjfcVK8rUhPLPaJ-HeGH9X_EfF-nEJn4',
    appId: '1:130658554754:android:29cc84917106cecc76f59b',
    messagingSenderId: '130658554754',
    projectId: 'fitness-e29b5',
    storageBucket: 'fitness-e29b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBxkClYCtXXxwMQHV86VfebfUJPTfVths',
    appId: '1:130658554754:ios:a227a4a1fc5b1c5476f59b',
    messagingSenderId: '130658554754',
    projectId: 'fitness-e29b5',
    storageBucket: 'fitness-e29b5.appspot.com',
    iosBundleId: 'com.example.myfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBxkClYCtXXxwMQHV86VfebfUJPTfVths',
    appId: '1:130658554754:ios:ae22b7a6c4a0239176f59b',
    messagingSenderId: '130658554754',
    projectId: 'fitness-e29b5',
    storageBucket: 'fitness-e29b5.appspot.com',
    iosBundleId: 'com.example.myfit.RunnerTests',
  );
}
